### ISSUE TITLE
清除数据库bug

### ISSUE THREAD

**Issue by 1173922902** [SEAFHMC/nonebot-plugin-who-at-me#13]
清除数据库永远是清除所有人的艾特记录
![image](https://user-images.githubusercontent.com/44056856/178640783-9691fb1b-9563-45f5-8232-655e201697f6.png)

**Comment by shacha086** [comment]
问问您的python版本是？

**Comment by shacha086** [comment]
https://github.com/SEAFHMC/nonebot-plugin-who-at-me/pull/14/commits/140339735d6b92933e5a8b3b79fcc7ff069d0d23
试试

**Comment by SEAFHMC** [comment]
已在新版插件更新修复
