### ISSUE TITLE
部分成员报错

### ISSUE THREAD

**Issue by YuuLuo** [SEAFHMC/nonebot-plugin-who-at-me#16]
部分成员执行谁艾特我后报错，具体报错为：
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 4854}, msg=EMPTY_NODES, retcode=100, status=failed, wording=未找到任何可发送的合并转发信息>
清除数据后回复正常
请问要怎么解决，或者如何加一个时限 比如3天之前的消息不返回？

**Comment by SEAFHMC** [comment]
有没有稳定复现的方式？ 或者提供一下日志。
