### ISSUE TITLE
使用三天后出现转发失败

### ISSUE THREAD

**Issue by Yonnemy2nd** [SEAFHMC/nonebot-plugin-who-at-me#17]
使用三天后，一些聊天频率比较高的群出现发送失败的情况，go-cqhttp 端显示“合并转发(群)消息发送失败: 账号可能被风控”，聊天频率比较低的群可以正常用。推测应该是转发的条数太多导致。也许应该加个只检测发送两三天之内的艾特消息的限制？使用上也会方便很多。

**Comment by SEAFHMC** [comment]
更新插件到0.2.6吧，加了合并转发的超时时间。可以自定义，默认3天。

**Comment by Yonnemy2nd** [comment]
config 里默认的天数是 reminder_expire_time: Optional[float] = None，启动时候会报错，需要改一下。
天数改成 2 的时候也有的人会发不出来，改成 1 就能发出来了，确认确实是消息条数多的问题。
